New feature: File download support
aminalaee/sqladmin pull request #702
Opened 2024-01-23 15:51 UTC by EnotShow

Now if the database value is the file path and the file exists it will be shown as a downloadable file

Before:
![image](https://github.com/aminalaee/sqladmin/assets/88674695/7b3daff1-67be-4f84-a2bc-6680a06f9611)
After:
![image](https://github.com/aminalaee/sqladmin/assets/88674695/9c8cb04e-d1b3-4a50-8e8e-864b61e3db9e)

Changes  affect templates: deteils.html, list.html

2024-01-26 15:27 UTC, agn-7 commented
This PR solves the #701 issue.

2024-02-01 19:50 UTC, EnotShow commented
I decided that the user wants to have not only a download method but a reading method too. Now, besides the download method, there's an additional option to open files directly in a browser.

Additionally, I've addressed a security concern from the previous version. Instead of using file paths in the URL, which is insecure.

Now the result looks like:
![image](https://github.com/aminalaee/sqladmin/assets/88674695/262ec855-371d-4fe1-a8f5-94d66111e531)

Please let me know when you check my MR. I'm will grateful for the feedback

2025-11-25 12:23 UTC, mmzeynalli commented
@korolenkowork maybe consider doing this as a `Field`, so that user can implement it with `form_overrides` instead of default behaviour. It is really nice feature, and consider adding support for CDN urls as well, not only local files.

2026-04-06 21:17 UTC, mmzeynalli commented
@korolenkowork any updates?

2026-05-20 09:29 UTC, mmzeynalli commented
@korolenkowork can we merge this logic with @maxim-f1 PR #999 ? Let's make this not default, but as type_formatter for user to use

2026-05-21 10:52 UTC, korolenkowork commented
@mmzeynalli worked on it long time ago, I'll try to have a look on it on Friday and let you know

2026-05-21 10:53 UTC, mmzeynalli commented
Yeah, we were passive for some time. Please do so, and let us know. Thanks!

2026-05-22 17:52 UTC, korolenkowork commented
<img width="1918" height="392" alt="image" src="https://github.com/user-attachments/assets/7f2d0a5c-041a-4b60-a654-081ecf84d1cd" />

<img width="1919" height="380" alt="image" src="https://github.com/user-attachments/assets/f381e7da-8aef-4ca9-8916-a57769a96598" />

2026-05-22 17:55 UTC, korolenkowork commented
@mmzeynalli I made needed updates, work as a charm with @maxim-f1 PR #999

2026-05-24 21:12 UTC, mmzeynalli commented
Looks nice! I will review it this week.

2026-05-26 12:47 UTC, mmzeynalli requested changes

2026-05-26 12:47 UTC, mmzeynalli commented on docs/working_with_templates.md
> -```
Why this was removed?

2026-05-26 12:47 UTC, mmzeynalli commented on sqladmin/application.py
> +                "/{identity}/{pk:path}/{column_name}/read/",
maybe /view?

2026-05-26 12:47 UTC, mmzeynalli commented on sqladmin/fields.py
> +    widget = widgets.TextInput()
There is URLInput in wtforms

2026-07-09 14:50 UTC, mmzeynalli commented
Unlike list/details/edit/delete flows, _get_file does not check is_accessible, can_view_details, or check_can_view_details.
So admin with limited access can request file content from models/rows they should not be able to view, if they can guess identity/pk/column_name.

Also, if there are two columns with let's say CDN urls, one if formatted, other is hidden (i.e. not exposed to admin, or exposed and hidden), then once can again download the hidden files. We need to verify the column names as well in download and read file endpoints

2026-07-10 23:21 UTC, mmzeynalli approved these changes

2026-07-13 08:51 UTC, merged